name: chengliao
description: Flutter chat client for Android and Windows
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter: { sdk: flutter }
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  file_picker: ^8.1.4
  flutter_webrtc: 1.5.1
  record: 7.1.1
  permission_handler: ^11.3.1
  stomp_dart_client: ^2.1.1
  universal_io: ^2.2.2
dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
